# Generated by Django 6.0.2 on 2026-02-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_doctorprofile_labprofile_patientprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="experience_years",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="hospital_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="license_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="allergies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="blood_type",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="chronic_diseases",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="family_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="height_cm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="past_diseases",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="weight_kg",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
