# Generated by Django 6.0.2 on 2026-02-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_doctorprofile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
    ]
