# Generated by Django 6.0.2 on 2026-02-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_prescription_prescriptionitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="pharmacy_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("READY", "Ready"),
                    ("COMPLETED", "Completed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
