# Generated by Django 6.0.2 on 2026-02-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0007_labtestrequest_lab"),
    ]

    operations = [
        migrations.AddField(
            model_name="labtestrequest",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="lab_results/"),
        ),
        migrations.AddField(
            model_name="labtestrequest",
            name="clinical_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="labtestrequest",
            name="reference_range",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="labtestrequest",
            name="result_value",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
