# Generated by Django 6.0.2 on 2026-02-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0008_labtestrequest_attachment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescription",
            name="bill_attachment",
            field=models.FileField(blank=True, null=True, upload_to="bills/"),
        ),
    ]
